name: testing nix stuff
run-name: ${{ gitea.actor }} is testing out Gitea Actions ðŸš€
on: [push]
jobs:
  nix:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ gitea.event_name }} event."
      - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by Gitea!"
      - run: echo "ðŸ”Ž The name of your branch is ${{ gitea.ref }} and your repository is ${{ gitea.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install SSH keys
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_GITEA_SSH_KEY }}
          # name: gitea_action
          # known_hosts: ${{ secrets.SSH_GITEA_KNOWN_HOSTS }}
          #- name: Fix SSH key
          # run: sed -i 's/\r$//g' /root/.ssh/gitea_action
      - name: set up hosts known
        run: echo ${{ secrets.GITEA_KNOWN_HOSTS }} >> /root/.ssh/known_hosts
      - name: List SSH dir
        run: ls /root/.ssh/
      - name: List files in the repository
        run: |
          ls ${{ gitea.workspace }}
      - name: test ssh
        run: ssh -p 2222 -T git@gitea.deepak.science
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - run: nix build --version
      - name: Setup Attic Cache
        uses: ryanccn/attic-action@3354ae812cb672e1381be4c7914204c44db53866
        with:
          endpoint: ${{ secrets.ATTIC_ENDPOINT }}
          cache: ${{ secrets.ATTIC_CACHE }}
          token: ${{ secrets.ATTIC_TOKEN }}
      - name: Build Nix Package
        run: nix flake check
