# Hardware configuration for shannon (Dell PowerEdge R730)
# Generated by nixos-generate-config — replace this file with the actual
# output from running `nixos-generate-config` on the installed system.
#
# To generate:
#   1. Boot NixOS installer on Shannon
#   2. Mount target filesystems under /mnt
#   3. Run: nixos-generate-config --root /mnt
#   4. Replace this file with /mnt/etc/nixos/hardware-configuration.nix
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # PLACEHOLDER — replace with output of nixos-generate-config
  # These values will be specific to Shannon's disk layout.

  boot.initrd.availableKernelModules = [
    "megaraid_sas" # PERC H730
    "ahci"
    "xhci_pci"
    "sd_mod"
  ];

  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # PLACEHOLDER: update device paths after running nixos-generate-config
  # Typical R730 with PERC RAID will appear as /dev/sda
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos"; # PLACEHOLDER
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot"; # PLACEHOLDER
    fsType = "vfat";
  };

  swapDevices = [ ]; # add if needed

  # Dell PowerEdge R730: dual E5-2600 v3/v4
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.enableRedistributableFirmware = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
