name: ci
on:
  push:
    branches: ['**']
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
        with:
          extra-conf: |
            extra-substituters = https://cache.saumon.network/proxmox-nixos
            extra-trusted-public-keys = proxmox-nixos:D9RYSWpQQC/msZUWphOY2I5RLH5Dd6yQcaHIuug7dWM=
      - name: Flake check
        run: nix flake check --print-build-logs
      - name: Build nixosWalrus (WSL)
        run: nix build --no-link --print-build-logs .#nixosConfigurations.nixosWalrus.config.system.build.toplevel
      - name: Build nixosEggYoke (WSL)
        run: nix build --no-link --print-build-logs .#nixosConfigurations.nixosEggYoke.config.system.build.toplevel
      - name: Build shannon (Proxmox)
        run: nix build --no-link --print-build-logs .#nixosConfigurations.shannon.config.system.build.toplevel
      - name: Build nixosVM
        run: nix build --no-link --print-build-logs .#nixosConfigurations.nixosVM.config.system.build.toplevel
